configuration:
  configuration_dir: "commons/config"
  template_dir:
  - "commons/templates"
  - ".moban.d"
  configuration: pyexcel_io.yaml
targets:
  - "docs/source/conf.py": "docs/source/conf.py"
  - setup.py: setup.py
  - .travis.yml: travis.yml.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
  - LICENSE: LICENSE.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - test.sh: test.sh.jj2
  - test.bat: test.sh.jj2
  - README.rst: README.rst
  - "docs/source/index.rst": "docs/source/index.rst"